<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Lead;

class DashboardController extends Controller
{
    public function index(Request $request)
    {
        $totalLeads = Lead::count();
        $wonDeals = Lead::whereHas('status', function($q) {
            $q->where('name', 'Won');
        })->count();
        
        $activeFollowups = \App\Models\Followup::where('status', 'Pending')->count();

        // Calculate Revenue (dummy budget sum for won deals)
        $revenue = Lead::whereHas('status', function($q) {
            $q->where('name', 'Won');
        })->sum('budget');

        // Chart 1: Sales Performance (Leads generated by Month for the last 6 months)
        $salesPerformance = Lead::select(\DB::raw("strftime('%m', created_at) as month"), \DB::raw('count(*) as count'))
            ->groupBy('month')
            ->orderBy('month', 'asc')
            ->get();

        // Chart 2: Lead Sources Distribution
        $leadSources = \DB::table('leads')
            ->join('lead_sources', 'leads.source_id', '=', 'lead_sources.id')
            ->whereNull('leads.deleted_at')
            ->select('lead_sources.name', \DB::raw('count(*) as value'))
            ->groupBy('lead_sources.name')
            ->get();

        return response()->json([
            'success' => true,
            'message' => 'Dashboard stats fetched successfully',
            'data' => [
                'total_leads' => $totalLeads,
                'won_deals' => $wonDeals,
                'active_followups' => $activeFollowups,
                'revenue' => $revenue,
                'sales_performance' => $salesPerformance,
                'lead_sources' => $leadSources
            ]
        ]);
    }

    public function clearAllData(Request $request)
    {
        \App\Models\LeadActivityLog::query()->forceDelete();
        \App\Models\Followup::query()->forceDelete();
        \App\Models\Lead::query()->forceDelete();

        return response()->json([
            'success' => true,
            'message' => 'All data cleared successfully'
        ]);
    }
}
